# Generated by Django 3.1.5 on 2022-03-04 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_name', models.CharField(default='BrandStorming', max_length=50)),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=300)),
                ('option1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('option2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('option3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('option4', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='TeamDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=100)),
                ('leader_email', models.EmailField(max_length=80)),
                ('leader_mobile', models.CharField(max_length=10)),
                ('member2_name', models.CharField(blank=True, max_length=100)),
                ('member2_email', models.EmailField(blank=True, max_length=80)),
                ('member3_name', models.CharField(blank=True, max_length=100)),
                ('member3_email', models.EmailField(blank=True, max_length=80)),
                ('isTeamAdded', models.BooleanField(default=False)),
                ('isQuizTaken', models.BooleanField(default=False)),
                ('isProductAllocated', models.BooleanField(default=False)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
