# Generated by Django 3.1.5 on 2022-03-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inqapp', '0002_auto_20220304_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='teamdetail',
            name='product',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
