# Generated by Django 3.1.5 on 2022-03-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inqapp', '0003_auto_20220305_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdetail',
            name='submission',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
